### ISSUE TITLE
SFT

### ISSUE THREAD

**Issue by eyuansu62** [OFA-Sys/gsm8k-ScRel#1]
Does SFT contain instruction tuning process?

**Comment by GanjinZero** [comment]
Only gsm8k fine tuning.

**Comment by eyuansu62** [comment]
Have you ever planned to verify your findings on more LLM such as codeLLM? Cause I guess codeLLM may points to different conclusion.

**Comment by GanjinZero** [comment]
Not actually. We will now focus on 65B and 70B LLaMA to verify more scaling related conclusions.
