### ISSUE TITLE
When will release 33b RFT model?

### ISSUE THREAD

**Issue by nuochenpku** [OFA-Sys/gsm8k-ScRel#11]
Thanks

**Comment by GanjinZero** [comment]
My internet so slow, I will upload them after uploading all 13B models.

**Comment by GanjinZero** [comment]
Uploading.

**Comment by nuochenpku** [comment]
thanks！---- Replied Message ----FromZheng ***@***.***>Date08/18/2023 10:51 ***@***.***> CcJerry ***@***.***>***@***.***>SubjectRe: [OFA-Sys/gsm8k-ScRel] When will release 33b RFT model? (Issue #11)
Uploading.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/OFA-Sys/gsm8k-ScRel/issues/11#issuecomment-1683261538",
"url": "https://github.com/OFA-Sys/gsm8k-ScRel/issues/11#issuecomment-1683261538",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by GanjinZero** [comment]
https://huggingface.co/OFA-Sys/gsm8k-rft-llama33b-u33b/tree/main/gsm8k-rft-llama33b-u33b
