### ISSUE TITLE
Release the RFT 7B model

### ISSUE THREAD

**Issue by wenhuchen** [OFA-Sys/gsm8k-ScRel#2]
Hi there, is there any chance to share with us your RFT-7B model?

**Comment by GanjinZero** [comment]
Sure， I will open-source RFT (k=100, U13B, U33B). The models are quite large, and I think I need some time for uploading them.

**Comment by wenhuchen** [comment]
Great. Would you mind uploading the 7B one to Huggingface first?

**Comment by GanjinZero** [comment]
I will do it, while I also need open-source license from the company. So RFT 7B could possibly not be uploaded in one day.

**Comment by GanjinZero** [comment]
OFA-Sys/gsm8k-rft-llama7b-u13b

**Comment by GanjinZero** [comment]
The uploading is very unstable, I will try to fix it...

**Comment by wenhuchen** [comment]
Thanks a lot!

**Comment by GanjinZero** [comment]
I'm still failing uploading, and I will try to fix it tomorrow.

**Comment by wenhuchen** [comment]
Hello, thanks for sharing the model. I'm able to load it now. So this model is LLaMa-1 7B, RFT on the 100 paths generated by 13B SFT model. Is that correct?  So the accuracy should be 49.3?

**Comment by GanjinZero** [comment]
> Hello, thanks for sharing the model. I'm able to load it now. So this model is LLaMa-1 7B, RFT on the 100 paths generated by 13B SFT model. Is that correct?  So the accuracy should be 49.3?

Generated by 7B 7b2 13b 13b2 with 100 paths each. Acc should be 49.3.

**Comment by GanjinZero** [comment]
Base model is llama1-7B.

**Comment by wenhuchen** [comment]
Would you mind also sharing the 7B SFT model? Thanks a lot!

**Comment by GanjinZero** [comment]
I can do it. But my internet is so slow. It costs some time.

**Comment by wenhuchen** [comment]
Never mind. I just reproduced your results and trained an SFT model on my own. Thanks a lot! The numbers are totally correct.

**Comment by GanjinZero** [comment]
Happy you can reproduce my results!
