### ISSUE TITLE
Missing test.py file

### ISSUE THREAD

**Issue by huijiawu0** [OFA-Sys/gsm8k-ScRel#3]
Hello,

Thank you for sharing the invaluable code. While attempting to replicate your work, I noticed that the test_7b_13b.sh script references a test.py file, but it seems to be missing from the repository. Would you be able to add this file? It would be immensely helpful for researchers like us who are trying to replicate your work.

Best

**Comment by GanjinZero** [comment]
Will check and add later today

**Comment by GanjinZero** [comment]
uploaded
